### ISSUE TITLE
bm_to_pathlist stuck in an infinite loop

### ISSUE THREAD

**Issue by cabanmichal** [tatarize/potrace#3]
Hi, 

I'm trying to trace an image of an ECG curve however the code below never finishes. It seems that the `findnext` function is always returning the same tuple and therefore the infinite loop in `bm_to_pathlist` never breaks. I'm not sure if the issue is in my code or in the package.

Thank you.

```python
import numpy as np
import potrace
from PIL import Image

img = Image.open("curve.png")
img = img.convert("P", dither=Image.NONE)

data = np.asarray(img)
bitmap = potrace.Bitmap(data)
path = bitmap.trace()
```
![curve](https://user-images.githubusercontent.com/11903384/141780550-b363ec94-1080-40cb-9014-8e0a40f5cc6e.png)

**Comment by dovewi** [comment]
same

**Comment by tatarize** [comment]
I tried `potracer -o e.svg ekg.png` and it finished correctly and instantly. I guess I'll try your script there.

**Comment by tatarize** [comment]
Yeah, okay, that did it. Lemme check up on that.

**Comment by tatarize** [comment]
Yeah, when I convert to "1" rather than P it works. So it's something about the code using the palette type and expecting something else that's breaking this.

**Comment by tatarize** [comment]
Yeah, wasn't expecting an int8 numpy array there. It reacted really strangely and could actually invert etc. It's corrected now.
