### ISSUE TITLE
Error when importing.

### ISSUE THREAD

**Issue by kjmeier3** [tatarize/potrace#6]
Import portrace bitmap gives answer :

 import portrace bitmap
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.

**Comment by tatarize** [comment]
This port is potracer and should not contain the `r` in the frist part. I'm not sure if that's pypi not letting you download that or something else weird. But, I retested and it currently works.
